### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by Nassir-Al** [Nassir-Al/capstone-project#1]

**Comment by Nassir-Al** [comment]
As a user 
I want a calendar 
to have an overview of my date



![Image](https://user-images.githubusercontent.com/109968270/190934348-97f0be85-2e1f-4b71-9fdc-5103af3d29c6.png)


## ac

- [ ] there is a calendar on the page
- [ ] the calendar is big and above the page

## tasks

- [ ] create a branch
- [ ] create a calendar
- [ ] position the calendar on the page

**Comment by AnH13-6** [comment]
Very short and clear! perfect! :)
