### ISSUE TITLE
accept section

### ISSUE THREAD

**Issue by Nassir-Al** [Nassir-Al/capstone-project#10]

**Comment by Nassir-Al** [comment]
As a user i want a section to accept so i can see wich person accepted my meeting  

![Image](https://user-images.githubusercontent.com/109968270/191955727-9f552fc1-aba8-4dfa-b5a1-3453657746a9.png)

## ac

- [ ] there is a accept section on the page
- [ ] the accept section is in my meeting card

## tasks

- [ ] create a branch
- [ ] create a accept section
- [ ] position the accept section on the meeting card

**Comment by mbosselmann** [comment]
Hi Nassir,
same here as I mentioned in your other user story. :) And your value proposition is not well formatted. Could you fix this?
