### ISSUE TITLE
Counter

### ISSUE THREAD

**Issue by Nassir-Al** [Nassir-Al/capstone-project#2]

**Comment by Nassir-Al** [comment]
As a user i want a counter so i can see how many person are confirmed my meeting




![Image](https://user-images.githubusercontent.com/109968270/190941437-5b6023c0-4aca-4e5e-9f15-51d164295a84.png)

## ac

- [ ] there is a counter on the page
- [ ] when a button is clicked, then the counter count
- [ ] the button is on the  meeting card

## tasks

- [ ] create a branch
- [ ] create a button
- [ ] position the button on the page

**Comment by AnH13-6** [comment]
Looks good, but is the button on your drawing above (the little arrows next to the number)? It sounds like it will be on another page? But it sounds good otherwise!
