### ISSUE TITLE
Bookmark

### ISSUE THREAD

**Issue by Nassir-Al** [Nassir-Al/capstone-project#3]

**Comment by Nassir-Al** [comment]
as a user i want to save my confirmed meeting, so i can find them later




![Image](https://user-images.githubusercontent.com/109968270/190943831-ee6d6ca8-568a-4041-b234-3713000b080f.png)




## ac

- [ ] there is a Bookmark on the page
- [ ] when a button is clicked, then the counter count
- [ ] the button is on the  meeting card

## tasks

- [ ] create a branch
- [ ] create a button
- [ ] Create a icone
- [ ] position the button on the meeting card

**Comment by AnH13-6** [comment]
Like before you write that the element is on the meeting card. But does this card already exists? Wouldn't it be better to create the card first and then add the button and the bookmark?
