### ISSUE TITLE
Add Button

### ISSUE THREAD

**Issue by Nassir-Al** [Nassir-Al/capstone-project#4]

**Comment by Nassir-Al** [comment]
As a user i want a opportunity to ad a new meeting card so i can make more meetings


![Image](https://user-images.githubusercontent.com/109968270/190944290-5ba44ea6-0896-414f-ba07-8ce5eb15595d.png)


## ac

- [ ] there is a button on the meeting card
- [ ] when a button is clicked, then a meeting card is created
- [ ] the button is on the page

## tasks

- [ ] create a branch
- [ ] create a button
- [ ] position the button on the page

**Comment by AnH13-6** [comment]
I think it might be better  to have an additional  task "add functionality to the card".

**Comment by AnH13-6** [comment]
Also, the meeting card still doesn't exist? 🤔
