### ISSUE TITLE
Delete Button

### ISSUE THREAD

**Issue by Nassir-Al** [Nassir-Al/capstone-project#5]

**Comment by Nassir-Al** [comment]
As a user i want to delete my meeting when it is finished so i have a beter overview 


![Image](https://user-images.githubusercontent.com/109968270/190945215-dbeffef3-d5da-4968-b049-826f3849c366.png)


## ac

- [ ] there is a button on the page
- [ ] when a button is clicked, then the finished meeting card will be deleted

## tasks

- [ ] create a branch
- [ ] create a button
- [ ] position the button on the page

**Comment by AnH13-6** [comment]
How can you have a button that deletes a meeting card without having a meeting card? 😆 Please let me know if I missed something!
