### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by Nassir-Al** [Nassir-Al/capstone-project#6]

**Comment by Nassir-Al** [comment]
As a user i want a title so i can see the impotant imformaton of my side


![Image](https://user-images.githubusercontent.com/109968270/190945376-26dadbbe-a3d5-4aa5-92fb-4e7afa1d959e.png)


## ac

- [ ] there is a Title on the page
- [ ] All important information is in the title
- [ ] the title is at the top of the page

## tasks

- [ ] create a branch
- [ ] create a Title
- [ ] position the title on the top of the page

**Comment by DanielGennat** [comment]
Hi Nassir :)
I think you could describe your user story more detailed.

Scribble:
Do you have to fulfill the Mobile First Design requirement? Then your scribble should look more like a mobile display.

AC:
Which page is displayed? Is it the page of a certain date? Then the important information would be something like the date and the name of the date.

Tasks:
Maybe you want the title to be sticky?
