### ISSUE TITLE
Comment Section

### ISSUE THREAD

**Issue by Nassir-Al** [Nassir-Al/capstone-project#7]

**Comment by Nassir-Al** [comment]
As a user i want section were i can comment so i can explain my cancellation 


![Image](https://user-images.githubusercontent.com/109968270/190945673-1ac16add-1f3c-4fad-a7ed-bb87d1ceaf91.png)


## ac

- [ ] there is a comment section on the page
- [ ] i can comment in the meeting card
- [ ] the comment section are on the meeting card

## tasks

- [ ] create a branch
- [ ] create a comment section
- [ ] position the comment section on the meeting card

**Comment by DanielGennat** [comment]
Hi Nassir :)
my suggestions:

Scribble:
- Add the card to your scribble to show the position of the comment section on the card.
- Mobile First Design? :)

ac:
- The input field should be empty after commenting.

tasks:
- I think a `form` with a submit button would be more detailed. Maybe you want to add the submit button to your scribble.
- Should the comment be limited to a certain number of characters?
