### ISSUE TITLE
Searchfield

### ISSUE THREAD

**Issue by Nassir-Al** [Nassir-Al/capstone-project#9]

**Comment by Nassir-Al** [comment]
As a user i want a searchfield were i can find my added meetings so i have a better overview


![Image](https://user-images.githubusercontent.com/109968270/191953004-b9a4e0af-4929-414c-afba-eb4c381bcd83.png)

## ac

- [ ] there is a searchfield on the page
- [ ] the searchfield is in my meeting card

## tasks

- [ ] create a branch
- [ ] create a searchfield
- [ ] position the searchfield on the meeting card

**Comment by mbosselmann** [comment]
Hi Nassir,
it would be cool to see where your searchfield will be shown on the meeting card. Maybe you show this in your wireframe? :)
